export enum ReducerType {
  SET_LOADING = "SET_LOADING",
  SEARCH_USERS = "SEARCH_USERS",
  CLEAR_USERS = "CLEAR_USERS",
  SET_ALERT = "SET_ALERT",
  GET_USER = "GET_USER",
  GET_REPOS = "GET_REPOS",
  REMOVE_ALERT = "REMOVE_ALERT",
}
